### ISSUE TITLE
Suggestion: add GitHub topic tags to repo

### ISSUE THREAD

**Issue by mhucka** [PennyLaneAI/pennylane-cirq#190]
Tiny and non-urgent suggestion: this repo's visibility might benefit from the addition of GitHub topic tags on the front page of the GitHub repo. (It currently has none.) Some possible tags as starting points:

* [quantum computing](https://github.com/topics/quantum-computing)
* [quantum algorithms](https://github.com/topics/quantum-algorithms)
* [quantum circuits](https://github.com/topics/quantum-circuits)
* [cirq](https://github.com/topics/cirq)

**Comment by josh146** [comment]
Thanks @mhucka, I've added some tags to this repository
