### ISSUE TITLE
Update expectation value computation logic 

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/pennylane-cirq#53]
Currently, the simulator device uses the following logic for expectation values:

```python
def expval(self, observable):
    if not hasattr(self._simulator, "simulate_expectation_values"):
        return super().expval(observable)
     return self._simulator.simulate_expectation_values(
        self.circuit, cirq.PauliSum() + self.to_paulistring(observable)
     )[0]
```

That is, if the simulator has the `simulate_expectation_values` attribute, this is used to compute the **exact** expectation values.

Note that **this ignores the shots/analytic argument**. So if the attribute exists, exact expectation values are always returned.

Pre-v0.10 of Cirq, this is fine, since `cirq.Simulator` does not have this attribute. However, we will need to revisit as soon as:

* The shots refactor is complete
* Cirq v0.10 is out.

**Comment by rmoyard** [comment]
This issue is solved by #81 .
