### ISSUE TITLE
The latest pennylane-cirq requires `simulate` method without `analytic` argument.

### ISSUE THREAD

**Issue by jaeyoo** [PennyLaneAI/pennylane-cirq#69]
On 0.14.0, there was `analytic` argument in `qml.device`, so we could set if `False` and then add `Cirq`-based simulators. However, the latest version has no `analytic`, and it always requires `simulate` method.

In details, when we run the colab [here](https://github.com/google/floq-client/blob/03f4351d5d0a82767d3d562f33970e063bfe14f5/docs/PennyLane_Cirq_with_Floq_Tutorial.ipynb), if we change the pennylane & pennylane-cirq versions to the latest, then it says:

```
AttributeError: 'CirqSimulator' object has no attribute 'simulate'.
```

**Comment by josh146** [comment]
Hi @jaeyoo! The latest version of PennyLane replaces the anlaytic keyword argument with `shots=None`. If you change to `shots=None` in the colab notebook, does it then work?

**Comment by jaeyoo** [comment]
Thank you @josh146 , I realized that the issue was caused by `shots=None`. After assigning some value to `shots` the error message's gone.

For the case of `shots=None` (or previously `analytic=True`), is `simulate()` mandatory? I mean, For the latest Cirq simulator, we can see:

[cirq.sim.SimulatesExpectationValues](https://quantumai.google/reference/python/cirq/sim/SimulatesExpectationValues).simulate_expectation_values()
[cirq.sim.SimulatesSamples](https://quantumai.google/reference/python/cirq/sim/SimulatesSamples).run()
[cirq.sim.SimulatesFiniteState](https://quantumai.google/reference/python/cirq/sim/SimulatesFinalState).simulate()

and it seems to accept `SimulatesFiniteState` simulator only. Is it mandatory? What about `SimulatesExpectationValues` simulator..?

**Comment by josh146** [comment]
Glad it worked!

> For the case of `shots=None` (or previously `analytic=True`), is `simulate()` mandatory?

I don't believe so, no; I think this is an artifact of the core of this plugin being written against an older Cirq version. If there are better ways of accessing expectation values with finite shots, we should mark the plugin for an update to access these more efficient methods.

**Comment by jaeyoo** [comment]
Thank you Josh, yes, I hope the latest PennyLane-Cirq supports the latest Cirq too. Could you please add this feature into it?

**Comment by josh146** [comment]
@jaeyoo I've created a new issue here (https://github.com/PennyLaneAI/pennylane-cirq/issues/70), so will close this one for now 🙂 Feel free to comment on the other one in case I have missed any details!

> I hope the latest PennyLane-Cirq supports the latest Cirq too

Just double checking, is anything broken using PennyLane with the latest Cirq version? Or is it more that there are newer features available?
