### ISSUE TITLE
Add support for the latest Cirq version, as well as additional simulators

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/pennylane-cirq#70]
The latest version of Cirq provides additional simulators for 'analytic' mode (`shots=None`), in particular

```
cirq.sim.SimulatesExpectationValues.simulate_expectation_values()
cirq.sim.SimulatesFinalState.simulate()
```

Support for `SimulatesExpectationValues` should be added to the PL-Cirq plugin, to ensure a more efficient pathway for computing expectation values when using `shots=None`.

**Comment by rmoyard** [comment]
This issue is solved by #81 .
